services:
  - type: web
    name: social-media-parser
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    disk:
      name: media
      mountPath: /usr/src/app/media
      sizeGB: 1 